"""Collect pinned framework source and rebuild/relink inputs for release users."""
import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import tarfile
import tempfile

ROOT = Path(__file__).resolve().parents[1]


def run(*args):
    subprocess.run(list(map(str, args)), check=True, cwd=ROOT)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    platformio = Path(os.environ.get('PLATFORMIO_CORE_DIR', Path.home() / '.platformio'))
    framework = platformio / 'packages/framework-arduinoespressif32'
    build = ROOT / 'firmware/.pio/build/crowpanel213'
    if not framework.is_dir() or not (build / 'firmware.elf').is_file():
        raise SystemExit('Build the pinned firmware before collecting release sources.')
    with tempfile.TemporaryDirectory(prefix='sweetmeter-relink-') as temporary:
        folder = Path(temporary) / 'Sweetmeter-firmware-rebuild'
        folder.mkdir()
        run('git', 'archive', '--format=tar', '--output', folder / 'Sweetmeter-source.tar', 'HEAD')
        # The exact installed SDK contains Espressif binary components and notices.
        shutil.copytree(framework, folder / 'framework-arduinoespressif32',
                        ignore=shutil.ignore_patterns('__pycache__', '*.pyc'))
        shutil.copytree(build, folder / 'application-objects',
                        ignore=shutil.ignore_patterns('.sconsign*'))
        for name, url, ref in [
            ('arduino-esp32-source', 'https://github.com/espressif/arduino-esp32.git', '2.0.17'),
            ('esp-idf-source', 'https://github.com/espressif/esp-idf.git', 'v4.4.7'),
        ]:
            run('git', 'clone', '--depth', '1', '--branch', ref, '--recurse-submodules',
                '--shallow-submodules', url, folder / name)
            for gitdir in sorted((folder / name).rglob('.git'), reverse=True):
                if gitdir.is_dir():
                    shutil.rmtree(gitdir)
                else:
                    gitdir.unlink()
        (folder / 'RELINKING.md').write_text(
            '# Firmware rebuild and relinking\n\n'
            'Contains the exact application object files, installed Arduino framework/SDK, '
            'Arduino 2.0.17 source and recursive ESP-IDF v4.4.7 source. Their licenses remain '
            'in their source trees. Extract Sweetmeter-source.tar, install PlatformIO 6.1.18 '
            'and run `pio run -d firmware`; platform espressif32 6.12.0 pins the toolchain. '
            'The generated public-key/version header is under application-objects or can '
            'be regenerated by the source build. To modify LGPL code, replace the relevant '
            'core/library files in the installed framework with your changes, run '
            '`pio run -d firmware -t clean`, then rebuild/relink and flash your own device. '
            'No signing private key is necessary for USB installation. The production '
            'BLE updater accepts only authorized release signatures; physical USB flashing '
            'remains available and secure boot is not enabled.\n', encoding='utf-8')
        generated = ROOT / 'firmware/.generated'
        if generated.is_dir():
            shutil.copytree(generated, folder / 'generated-public-build-headers')
        target = args.output / 'Sweetmeter-firmware-rebuild.tar.gz'
        with tarfile.open(target, 'w:gz') as archive:
            archive.add(folder, arcname=folder.name)
        print(target)


if __name__ == '__main__':
    main()
