"""Generate Sweetmeter UI 6x11 from bundled Liberation Mono (OFL-1.1).

This is a converted/subset font called Sweetmeter UI, not the original font.
Run with Pillow from requirements.txt; no system font or network is used.
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]


def main():
    face = ImageFont.truetype(str(ROOT / 'meter/assets/fonts/LiberationMono-Regular.ttf'), 9)
    lines = [
        '#pragma once',
        '// Sweetmeter UI 6x11, generated by scripts/generate_screen_font.py.',
        '// Converted from Liberation Mono 2.1.5; SPDX-License-Identifier: OFL-1.1.',
        '// Digitized data copyright (c) 2010 Google Corporation.',
        '// Copyright (c) 2012 Red Hat, Inc.',
        '// Full notice/license: meter/assets/fonts/LICENSE; see THIRD_PARTY_NOTICES.md.',
        'const uint8_t screenFont[95][11] = {',
    ]
    for code in range(32, 127):
        glyph = Image.new('1', (6, 11), 0)
        ImageDraw.Draw(glyph).text((0, 8), chr(code), anchor='ls', font=face, fill=1)
        rows = [sum((1 << (5 - x)) if glyph.getpixel((x, y)) else 0
                    for x in range(6)) for y in range(11)]
        lines.append('  {' + ', '.join(map(str, rows)) + f'}}, // U+{code:04X}')
    lines.append('};')
    (ROOT / 'firmware/src/screen_font.h').write_text('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
